const users = [
    {
        isAdmin: true,
        name: {
            first: "RivkiO",
            middle: "",
            last: "Oz",
        },
        phone: "0507123012",
        email: "rivkio@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Tel aviv",
            street: "Shoham",
            houseNumber: 5,
            zip: "8920435",
        },
        isBusiness: true,
    },
    {
        isAdmin: false,
        name: {
            first: "Avi",
            middle: "",
            last: "Oz",
        },
        phone: "0507123013",
        email: "avi@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Ramat gan",
            street: "Shoham",
            houseNumber: 6,
            zip: "8920436",
        },
        isBusiness: true,
    },
    {
        isAdmin: false,
        name: {
            first: "Dassi",
            middle: "",
            last: "Madmon",
        },
        phone: "0507123014",
        email: "dassi@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Holon",
            street: "Shoham",
            houseNumber: 7,
            zip: "8920437",
        },
        isBusiness: false,
    },
];
const products = [
    {
        productName: "Floral Summer Dress for Girls",
        subtitle: "Light and comfortable summer dress",
        productDescription: "Light and comfortable summer dress made of 100% high-quality cotton with a colorful floral print. The dress features short sleeves and an A-line silhouette, perfect for hot summer days. Convenient back button closure.",
        price: 99,
        color: "Pink with colorful flowers",
        sizes: [2, 4, 6, 8, 10, 12],
        model: "2024-KID-DRS-PRT",
        ages: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        web: "https://www.bing.com",
        image: {
            url: "https://www.carouselwear.com/products/a-basket-of-pink-roses-baby-dress",
            alt: "Floral Summer Dress",
        },
        category: "girls",
        quantity: 10,
    },
    {
        productName: "Kids' T-Shirt",
        subtitle: "Light and comfortable kids' t-shirt",
        productDescription: "Light and comfortable kids' t-shirt made of 100% breathable cotton with a subtle star print. The t-shirt comes in various colors with short sleeves, suitable for all seasons.",
        price: 49,
        color: "Blue, Green, Red, White",
        sizes: [2, 4, 6, 8, 10, 12, 14],
        model: "2024-KID-TEE-STR",
        ages: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        web: "https://www.bing.com",
        image: {
            url: "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_41.jpg",
            alt: "Kids' T-Shirt",
        },
        category: "boys",
        quantity: 10,
    },
    {
        productName: "Kids' Shorts",
        subtitle: "Shorts made of soft and comfortable cotton",
        productDescription: "Shorts made of 100% soft and comfortable cotton, with side pockets and a drawstring waist for perfect fit. Available in various colors, suitable for summer activities and outdoor play.",
        price: 69,
        color: "Dark Blue, Grey, Green",
        sizes: [2, 4, 6, 8, 10, 12],
        model: "2024-KID-SHR-CO",
        ages: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        web: "https://www.bing.com",
        image: {
            url: "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
            alt: "Kids' Shorts",
        },
        category: "boys",
        quantity: 10,
    },

];
export { users, products };