const users = [
    {
        isAdmin: true,
        name: {
            first: "RivkiO",
            middle: "",
            last: "Oz",
        },
        phone: "0507123012",
        email: "rivkio@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Tel aviv",
            street: "Shoham",
            houseNumber: 5,
            zip: "8920435",
        },
        isBusiness: true,
    },
    {
        isAdmin: false,
        name: {
            first: "Avi",
            middle: "",
            last: "Oz",
        },
        phone: "0507123013",
        email: "avi@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Ramat gan",
            street: "Shoham",
            houseNumber: 6,
            zip: "8920436",
        },
        isBusiness: true,
    },
    {
        isAdmin: false,
        name: {
            first: "Dassi",
            middle: "",
            last: "Madmon",
        },
        phone: "0507123014",
        email: "dassi@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Holon",
            street: "Shoham",
            houseNumber: 7,
            zip: "8920437",
        },
        isBusiness: false,
    },
];
const cards = [
    {
        title: "a wonderful new card",
        subtitle: "a test value for this card",
        description: "a test value for new card\na test value for new card\n",
        phone: "050-3211234",
        email: "qwe@gmail.com",
        web: "https://www.bing.com",
        image: {
            url: "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
            alt: "image of something",
        },
        address: {
            state: "IL",
            country: "Israel",
            city: "Tel aviv",
            street: "Shoham",
            houseNumber: 5,
            zip: "8920435",
        },
    },
    {
        title: "a wonderful new card2",
        subtitle: "a test value for this card",
        description: "a test value for new card\na test value for new card\n",
        phone: "050-3211235",
        email: "qwf@gmail.com",
        web: "https://www.bing.com",
        image: {
            url: "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_35.jpg",
            alt: "image of something",
        },
        address: {
            state: "IL",
            country: "Israel",
            city: "Ramat gan",
            street: "Shoham",
            houseNumber: 6,
            zip: "8920436",
        },
    },
    {
        title: "a wonderful new card3",
        subtitle: "a test value for this card",
        description: "a test value for new card\na test value for new card\n",
        phone: "050-321126",
        email: "qwg@gmail.com",
        web: "https://www.bing.com",
        image: {
            url: "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_40.jpg",
            alt: "image of something",
        },
        address: {
            state: "IL",
            country: "Israel",
            city: "Holon",
            street: "Shoham",
            houseNumber: 7,
            zip: "8920437",
        },
    },
];
export { users, cards };